SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID

#NOT : 앞에서 아니라고 먼저 선언하기
WHERE NOT INTAKE_CONDITION = 'Aged'

#NOT IN : 안에 들어있지 않음
WHERE INTAKE_CONDITION NOT IN ('Aged')