SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER


-- INNER JOIN으로 풀기

FROM FIST_HALF F
    INNER JOIN ICECREAM_INFO I 
    ON F.FLAVOR = I.FLAVOR