SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog' AND NAME LIKE '%EL%'
ORDER BY NAME ASC

-- SQL은 따옴표를 사용해야 함
-- 하지만 대문자, 소문자를 구분할 필요없음

-- 오라클은 소문자로 바꿔줘야 함
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
WHERE LOWER(NAME) LIKE '%el%' AND ANIMAL_TYPE='Dog'
ORDER BY NAME;